version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      - phpmyadmin
      - db-postgres
      - db-mysql
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: mariadb-nginx-proxy-manager
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql_maria:/var/lib/mysql

  db-mysql:
    image: "mysql:latest"
    container_name: mysql-nginx-proxy-manager
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: npm
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33065:3306"
    volumes:
        - ./mysql:/var/lib/mysql
        
  db-postgres:
    image: "postgres:15.5-bullseye"
    container_name: postgres-nginx-proxy-manager
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Nvidiaakun07#
    ports:
      - "5432:5432"
    volumes:
        - ./postgres:/var/lib/postgresql
        
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-nginx-proxy-manager
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    external: true
    name: proxy_network
